### ISSUE TITLE
Elixir potentially uninstalling the default logger?

### ISSUE THREAD

**Issue by michaeljones** [lpil/logging#1]
I raised this on Discord. I'm not directly using the `logging` library to my knowledge but it was suggested that I make this issue here.

I'm making a web backend with wisp. I've just added antigone for password hashing and now when I run `gleam run`, I get:

```
   Compiled in 0.19s
    Running backend.main
exception error: no match of right hand side value {error,{not_found,default}}
  in function  logging_ffi:configure/0 (/home/michael/root/projects/doable/backend/build/dev/erlang/logging
/_gleam_artefacts/logging_ffi.erl, line 14)
  in call from backend:main/0 (/home/michael/root/projects/doable/backend/build/dev/erlang/backend/_gleam_a
rtefacts/backend.erl, line 8)%
```
Antigone relies on Elixir modules and it was your conclusion that maybe Elixir is uninstalling the default logging set up and so things are failing.

Edit: Commenting out `wisp.configure_logger()` is enough to unblock me for the moment.

**Comment by lpil** [comment]
Thank you
